# Generated by Django 4.2 on 2023-05-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luna", "0002_post_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=200, verbose_name="Фамилия")),
                ("email", models.EmailField(max_length=200)),
                (
                    "message",
                    models.TextField(max_length=1000, verbose_name="Сообщение"),
                ),
            ],
        ),
    ]
